# Generated by Django 5.1.6 on 2025-02-12 17:03

import django.core.validators
from django.db import migrations, models

import referral_cods.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{6}$", "Код должен состоять из 6 цифр"
                            )
                        ],
                        verbose_name="Реферальный код",
                    ),
                ),
                (
                    "validity_period",
                    models.DateField(
                        validators=[referral_cods.validators.validate_date_in_past],
                        verbose_name="Срок действия реферального кода",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Активность реферального кода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Реферальный код",
                "verbose_name_plural": "Реферальные коды",
                "ordering": ("id",),
            },
        ),
    ]
